### ISSUE TITLE
2.0 Release

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI-Rails-LESS#11]
Just wanted to ping you that 2.0 has been released. I'd like to add your repo to my integration guide. 

Would you consider moving it over to Semantic-Org?

**Comment by LimeBlast** [comment]
:+1:

**Comment by tnypxl** [comment]
+1

**Comment by maxd** [comment]
@jlukic Yes, this is good idea.

**Comment by maxd** [comment]
@jlukic As I understand I [should have admin right](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization) in Semantic-Org organization to transfer repository. Could you please provide it?

**Comment by jlukic** [comment]
I've sent you an invite to a new rails team which will has access to this reserved repo https://github.com/Semantic-Org/Semantic-UI-Rails-LESS

**Comment by maxd** [comment]
I have transferred repository to Semantic-Org organization but can't rename it to Semantic-UI-Rails-LESS (seems like need to remove empty repository with same name). Could you please do it?

**Comment by maxd** [comment]
FYI: I will be unavailable all next week.

**Comment by jlukic** [comment]
I've adjusted the name. Thanks for the update on your availability. Take your time and thanks for the help.
