### ISSUE TITLE
Artifacts in the popup's 

### ISSUE THREAD

**Issue by postbud** [Semantic-Org/Semantic-UI-Rails-LESS#13]
Loading json data in 'popups' outer layer as text with characters '\n', '\', etc.
If everything is correct:
![correct](https://cloud.githubusercontent.com/assets/12687205/8748974/a7aab758-2cb7-11e5-9faa-4666a49b6015.jpg)

but more often:
![incorrect](https://cloud.githubusercontent.com/assets/12687205/8748992/c7b0b84a-2cb7-11e5-8604-1f4dabe7c994.jpg)

To correctly view the need to refresh the page.

**Comment by maxd** [comment]
Use [Semantic-UI issue tracker](https://github.com/Semantic-Org/Semantic-UI/issues) for such kind of problems related to framework behavior.
