### ISSUE TITLE
Version 2.0.8

### ISSUE THREAD

**Issue by caiotarifa** [Semantic-Org/Semantic-UI-Rails-LESS#15]
Let's upgrade to `2.0.8`?

https://github.com/Semantic-Org/Semantic-UI/blob/master/RELEASE-NOTES.md

I would like to contribute with this, but I don't know how. There is any documentation about it?

Thank you!

**Comment by maxd** [comment]
SU 2.0.8 doesn't have changes in CSS.

**Comment by jlukic** [comment]
Yep.
