### ISSUE TITLE
Customizing semantic ui files

### ISSUE THREAD

**Issue by adavia** [Semantic-Org/Semantic-UI-Rails-LESS#20]
I am a bit confused with this "If you wish to change component variables or extend components you can just configure corresponding config/{collections,elements, globals,modules,views}/*.{overrides,variables} files." In my case i need to change a couple of things in segment.overrides i guess.. so how i am suppose to do that? Importing my assets in the file? Adding css in the file? Any example would be appreciated. Thanks

**Comment by maxd** [comment]
See [Theming](http://semantic-ui.com/usage/theming.html) section in Semantic UI documentation.
