### ISSUE TITLE
error evaluating function `darken`: Object #<Object> has no method 'toHSL'

### ISSUE THREAD

**Issue by krtschmr** [Semantic-Org/Semantic-UI-Rails-LESS#26]
Fresh installed Gem throwing the error

* 2.1.8.2
* 3.22

  
gem 'less-rails-semantic_ui'
gem 'autoprefixer-rails'

bundle install

rails s

  (in /home/tim/.rvm/gems/ruby-2.1.6/gems/less-rails-semantic_ui-2.1.8.2/assets/stylesheets/semantic_ui/definitions/modules/accordion.less)

**Comment by krtschmr** [comment]
2.1.7.0 working

**Comment by krtschmr** [comment]
so 2170 works, but unfortunately


Compiled semantic_ui/definitions/modules/shape.css  (10295ms)  (pid 23756)
Compiled semantic_ui/definitions/modules/sidebar.css  (7439ms)  (pid
 23756)
Compiled semantic_ui/definitions/globals/site.css  (9280ms)  (pid 23756)
Compiled semantic_ui/definitions/views/statistic.css  (7841ms)  (pid 23756)
Compiled semantic_ui/definitions/elements/step.css  (8619ms)  (pid 23756)
Compiled semantic_ui/definitions/modules/sticky.css  (9327ms)  (pid 23756)
Completed   in 278369.5ms

dang slow.

**Comment by maxd** [comment]
Didn't get your problem. Try to explain it more detail as recommended in issue template (include full backtrace of error).

**Comment by krtschmr** [comment]
with 2.1.8.2 and rails 3.22 the server is not starting. 

the error message is

error evaluating function `darken`: Object #<Object> has no method 'toHSL'
coming from (in /home/tim/.rvm/gems/ruby-2.1.6/gems/less-rails-semantic_ui-2.1.8.2/assets/stylesheets/semantic_ui/definitions/modules/accordion.less)

**Comment by maxd** [comment]
Could you please provide test Rails project for reproduce this problem?
