### ISSUE TITLE
"DEPRECATION WARNING: Sprockets method `register_engine` is deprecated."

### ISSUE THREAD

**Issue by jkgatt** [Semantic-Org/Semantic-UI-Rails-LESS#36]
### Subject of the issue
Whenever I try to include all the gem's required, 2 deprecation warnings with regards to the Sprockets and LESS.

There is no error shown, like in #32, just the deprecation warning.

### Your environment
Gem Versions:
- gem 'less-rails-semantic_ui', '~> 2.2', '>= 2.2.10.0'
- gem 'autoprefixer-rails', '~> 6.7', '>= 6.7.7.2'
- gem 'therubyracer', '~> 0.12.3'

Rails Version: 5.0.2

### Steps to reproduce
Just by following the instructions on the README.md file and trying to any command (such as: rails server).

### Expected behaviour
No deprecation warnings shown

### Actual behaviour
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /Users/jeangatt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/less-rails-2.7.1/lib/less/rails/railtie.rb:15)
DEPRECATION WARNING: You are using the a deprecated processor interface Less::Rails::ImportProcessor.
Please update your processor interface:
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from block in <class:Railtie> at /Users/jeangatt/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/less-rails-2.7.1/lib/less/rails/railtie.rb:20)

**Comment by jkgatt** [comment]
Have looked further into this and it is a problem with the less-rails gem.

**Comment by Noeltim** [comment]
hey @jkgatt have you managed to resolve this? I am getting the same error messages and would like to know if you have found a workaround?
