### ISSUE TITLE
Incompatibility with latest autoprefixer-rails

### ISSUE THREAD

**Issue by jefmathiot** [Semantic-Org/Semantic-UI-Rails-LESS#52]
Versions >= `9.1.4` of the `autoprefixer-rails` gem have deprecated `therubyracer` as the runtime. See https://github.com/ai/autoprefixer-rails/blob/master/lib/autoprefixer-rails/processor.rb#L149

Unfortunately, the `less.rb` does not seem to support the `mini_racer` runtime.

The workaround is to explicitely lock the `autoprefixer-rails` to 6.3.7. I'd be glad to submit a PR, but as the dependency has to be manually added to the Gemfiles and is not present in the gemspec, I'm not sure how I could efficiently fix the issue.

**Comment by brendon** [comment]
I think you'd have to just lock that in your own Gemfile because, as you say, it's not one of our dependencies.

**Comment by ctilley83** [comment]
Yes it is one of your dependencies.

**Comment by brendon** [comment]
`autoprefixer-rails` isn't one of our dependencies, but `therubyracer` is a development dependency in the gemspec. The only fix we could do would be to mention that specific version of `autoprefixer-rails` in the readme.

This gem is becoming unviable for other reasons: https://github.com/Semantic-Org/Semantic-UI-Rails-LESS/issues/53.

I think perhaps moving away from `less.rb` would be the proper cure. I no longer use this gem, not have the time for a fix that big, but if you want to work on a PR that moves it away from less.rb, please do :) I'm certainly happy to help review things etc...
